url: http://indiq.org

# Site settings
title: IndiQ Meetups
email: your-email@domain.com
description: "Quantum computing community across India"


# Team names, titles and social links
people:
- name: Samanvay Sharma
  pic: samanvay
  city: New Delhi
  social:
    - title: twitter
      url: https://twitter.com/AnsatzX
    - title: linkedin
      url: https://www.linkedin.com/in/samanvay-sharma/
    - title: github
      url: https://github.com/starktech23

- name: Rana Prathap
  pic: rana
  city: Hyderabad
  social:
    - title: twitter
      url: https://twitter.com/RanaPrathapSimh
    - title: linkedin
      url: https://www.linkedin.com/in/ranaprathapsimh/
    - title: github
      url: https://github.com/Yoghurtyam

- name: Frederik Hardervig
  pic: frederik
  city: Hyderabad
  social:
    - title: twitter
      url: https://twitter.com/FredHardervig
    - title: linkedin
      url: https://www.linkedin.com/in/frederikhardervig/
    - title: github
      url: https://github.com/Fhardervig

- name: Rahul Pratap Singh
  pic: rahul
  city: Kolkata
  social:
    - title: twitter
      url: https://twitter.com/RahulPSingh3
    - title: linkedin
      url: https://www.linkedin.com/in/rahul-pratap-singh-1a31a5138/
    - title: github
      url: https://github.com/Rahps97

- name: Radha Pyari Sandhir
  pic: radha
  city: Delhi
  social:
    - title: twitter
      url: https://twitter.com/RadhaPyari
    - title: linkedin
      url: https://www.linkedin.com/in/radha-pyari-sandhir/
    - title: github
      url: https://github.com/quantum-kittens

- name: Kiran Johns
  pic: kiran
  city: Kerala
  social:
    - title: twitter
      url: https://twitter.com/thetronjohnson
    - title: linkedin
      url: https://www.linkedin.com/in/kiranjohns/
    - title: github
      url: https://github.com/thetronjohnson


# Sponsors
sponsors:
  - name: qiskit
    url: https://qiskit.org/
  - name: ibm
    url: https://www.ibm.com/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/IndiQmeetups
  - title: discord
    url: https://discord.gg/Dn3rMu5
  - title: meetup
    url: https://www.meetup.com/IndiQ-Meetups/
  - title: youtube
    url: https://www.youtube.com/channel/UCrGwYEY1Y4pgTe1jCopu6NQ/
  - title: slack
    url: https://join.slack.com/t/qiskit/shared_invite/enQtODQ2NTIyOTgwMTQ3LTI0NzM2NzkzZjJhNDgzZjY5MTQzNDY3MGNiZGQzNTNkZTE4Nzg1MjMwMmFjY2UwZTgyNDlmYWQwYmZjMjE1ZTM
  - title: github
    url: https://github.com/IndiQ-Meetups

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

future: true
